import Foundation

// MARK: - Job Sheet Data

/// Summary data for a printable job sheet.
public struct JobSheetData: Codable, Sendable {
    
    public let jobName: String
    public let material: String
    public let sheetWidth: Double      // mm
    public let sheetHeight: Double      // mm
    public let toolpaths: [ToolpathInfo]
    public let createdAt: Date
    public let notes: String
    
    public init(
        jobName: String,
        material: String,
        sheetWidth: Double,
        sheetHeight: Double,
        toolpaths: [ToolpathInfo],
        createdAt: Date = .now,
        notes: String = ""
    ) {
        self.jobName = jobName
        self.material = material
        self.sheetWidth = sheetWidth
        self.sheetHeight = sheetHeight
        self.toolpaths = toolpaths
        self.createdAt = createdAt
        self.notes = notes
    }
}

// MARK: - Toolpath Info

/// A single toolpath entry on the job sheet.
public struct ToolpathInfo: Codable, Sendable, Identifiable {
    
    public let id: UUID
    public let name: String
    public let type: ToolpathType
    public let tool: String
    public let feedRate: Double      // mm/min
    public let depth: Double          // mm
    public let estimatedTime: Double  // seconds
    
    public enum ToolpathType: String, Codable, Sendable {
        case profile
        case pocket
        case drill
        case vcarve
        case quickengrave
        
        public var displayName: String {
            switch self {
            case .profile: return "Profile"
            case .pocket: return "Pocket"
            case .drill: return "Drill"
            case .vcarve: return "V-Carve"
            case .quickengrave: return "Quick Engrave"
            }
        }
    }
    
    public init(
        id: UUID = UUID(),
        name: String,
        type: ToolpathType,
        tool: String,
        feedRate: Double,
        depth: Double,
        estimatedTime: Double
    ) {
        self.id = id
        self.name = name
        self.type = type
        self.tool = tool
        self.feedRate = feedRate
        self.depth = depth
        self.estimatedTime = estimatedTime
    }
}

// MARK: - Job Sheet Generator

/// Generates a printable PDF job sheet from JobSheetData.
///
/// The PDF includes:
/// - Job name and material header
/// - Sheet dimensions
/// - Toolpath table (name, type, tool, feed rate, depth, estimated time)
/// - Notes section
/// - Timestamp
///
/// Uses a minimal PDF writer — no external dependencies required.
public struct JobSheetGenerator {
    
    /// Generate a PDF job sheet from the given data and write it to the specified URL.
    ///
    /// - Parameters:
    ///   - data: The job sheet data to render.
    ///   - outputPath: URL where the PDF should be written (e.g. in the user's Documents folder).
    /// - Returns: `true` if the PDF was generated and written successfully, `false` on failure.
    public static func generatePDF(data: JobSheetData, outputPath: URL) -> Bool {
        do {
            let pdfData = try buildPDF(data: data)
            try pdfData.write(to: outputPath)
            return true
        } catch {
            return false
        }
    }
    
    /// Build the PDF as Data bytes.
    private static func buildPDF(data: JobSheetData) throws -> Data {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short
        
        let dateStr = dateFormatter.string(from: data.createdAt)
        let footerStr = "Generated by ShopPilot — \(dateFormatter.string(from: .now))"
        
        // PDF structure: objects with cross-references
        var objects: [String] = []
        var offsets: [Int] = []
        
        // Helper to add object
        func addObject(_ content: String) -> Int {
            let objNum = objects.count + 1
            offsets.append(0) // placeholder
            objects.append(content)
            return objNum
        }
        
        // Helper to add object with explicit number
        func addObject(_ content: String, number: Int) {
            while offsets.count < number {
                offsets.append(0)
                objects.append("")
            }
            offsets[number - 1] = 0 // placeholder, will fix
            objects[number - 1] = content
        }
        
        // Object 1: Catalog
        let catalogObj = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        addObject(catalogObj)
        
        // Object 2: Pages (placeholder, will rebuild)
        // We'll build content objects first, then Pages, then fix offsets
        
        // Content object: Title
        var contentStream = ""
        contentStream += "BT\n/F1 18 Tf\n0 0 Td\n(\(data.jobName)) Tj\nET\n"
        contentStream += "BT\n/F1 12 Tf\n0 0 Td\n(Job Sheet) Tj\nET\n"
        contentStream += "BT\n/F1 10 Tf\n0 -25 Td\n(Job:) Tj\nBT\n/F2 10 Tf\n50 -25 Td\n(\(data.jobName)) Tj\nET\n"
        contentStream += "BT\n/F1 10 Tf\n0 -15 Td\n(Material:) Tj\nBT\n/F2 10 Tf\n65 -15 Td\n(\(data.material)) Tj\nET\n"
        contentStream += "BT\n/F1 10 Tf\n0 -15 Td\n(Sheet Size:) Tj\nBT\n/F2 10 Tf\n75 -15 Td\n(\(String(format: "%.1f × %.1f mm", data.sheetWidth, data.sheetHeight))) Tj\nET\n"
        contentStream += "BT\n/F1 10 Tf\n0 -15 Td\n(Date:) Tj\nBT\n/F2 10 Tf\n40 -15 Td\n(\(dateStr)) Tj\nET\n"
        
        // Toolpath table header
        contentStream += "BT\n/F1 10 Tf\n0 -30 Td\n(Toolpaths) Tj\nET\n"
        
        // Table header row
        let headers = ["Name", "Type", "Tool", "Feed (mm/min)", "Depth (mm)", "Time (min)"]
        let colStartX: [Double] = [30, 140, 230, 310, 390, 460]
        var headerY: Double = -50
        var headerX: Double = 30
        for header in headers {
            contentStream += "BT\n/F1 9 Tf\n\(headerX) \(headerY) Td\n(\(header)) Tj\nET\n"
            headerX += 80
        }
        
        // Table data rows
        for (i, tp) in data.toolpaths.enumerated() {
            var rowY = headerY - 15 * (Double(i) + 1)
            var x = 30
            let cells = [
                tp.name,
                tp.type.displayName,
                tp.tool,
                String(format: "%.0f", tp.feedRate),
                String(format: "%.2f", tp.depth),
                String(format: "%.1f", tp.estimatedTime / 60.0)
            ]
            for cell in cells {
                contentStream += "BT\n/F2 9 Tf\n\(x) \(rowY) Td\n(\(cell)) Tj\nET\n"
                x += 80
            }
        }
        
        // Notes
        contentStream += "BT\n/F1 10 Tf\n0 -25 Td\n(Notes) Tj\nET\n"
        if !data.notes.isEmpty {
            contentStream += "BT\n/F2 9 Tf\n0 -15 Td\n(\(data.notes)) Tj\nET\n"
        }
        
        // Footer
        contentStream += "BT\n/F1 8 Tf\n0 -30 Td\n(\(footerStr)) Tj\nET\n"
        
        // Content object
        let contentObj = "3 0 obj\n<< /Length \(contentStream.count) >>\nstream\n\(contentStream)endstream\nendobj\n"
        addObject(contentObj)
        
        // Font objects
        let fontObj1 = "4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>\nendobj\n"
        addObject(fontObj1)
        let fontObj2 = "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding /FontDescriptor 6 0 R >>\nendobj\n"
        addObject(fontObj2)
        
        // Font descriptor
        let fontDescObj = "6 0 obj\n<< /Type /FontDescriptor /FontName /Helvetica /Flags 32 /ItalicAngle 0 /Ascent 750 /Descent -250 /CapHeight 750 /AvgWidth 400 /MaxWidth 800 /FontWeight 400 /StemV 40 >>\nendobj\n"
        addObject(fontDescObj)
        
        // Pages object
        let pagesObj = "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        addObject(pagesObj)
        
        // Build PDF with correct offsets
        var pdf = "%PDF-1.4\n"
        var currentOffset = pdf.utf8.count
        
        for obj in objects {
            let objData = obj.utf8
            pdf.append(obj)
        }
        
        // Cross-reference table
        let xrefOffset = pdf.utf8.count
        pdf += "xref\n0 \(objects.count + 1)\n"
        pdf += "0000000000 65535 f \n"
        for offset in offsets {
            pdf += String(format: "%010d 00000 n \n", offset)
        }
        
        pdf += "trailer\n<< /Size \(objects.count + 1) /Root 1 0 R >>\nstartxref\n\(xrefOffset)\n%%EOF\n"
        
        return Data(pdf.utf8)
    }
}
