import Foundation

// MARK: - HTML job-sheet template engine (SPK-1135)

/// Bundled A4 job-sheet HTML template with `{{PLACEHOLDER}}` tokens, filled
/// from `JobSheetData` by `JobSheetHTMLTemplateEngine`. The filled HTML is
/// rendered to PDF by the app (WebKit `WKWebView.createPDF`); the engine
/// itself is pure string substitution so it is fully CLT-testable.
///
/// Tokens:
///   {{JOB_NAME}}  {{MATERIAL}}  {{SHEET_WIDTH}}  {{SHEET_HEIGHT}}
///   {{DATE}}      {{NOTES}}     {{TOOLPATH_ROWS}}  {{FOOTER}}
///
/// `{{TOOLPATH_ROWS}}` expands to one `<tr>` per toolpath from
/// `JobSheetData.toolpaths`. All substituted values are HTML-escaped.
public struct JobSheetHTMLTemplateEngine {

    /// The bundled A4 template (letterhead-style). Self-contained CSS,
    /// A4 page size; printable via the PDF render path.
    public static let bundledTemplate: String = """
    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <style>
      @page { size: A4; margin: 18mm; }
      body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 11pt; }
      h1 { font-size: 17pt; margin: 0 0 2mm 0; }
      .subtitle { color: #666; font-size: 10pt; margin-bottom: 6mm; }
      table { border-collapse: collapse; width: 100%; margin-top: 5mm; }
      th, td { border: 1px solid #bbb; padding: 2mm 3mm; text-align: left; font-size: 9.5pt; }
      th { background: #f0f0f0; }
      .meta { display: grid; grid-template-columns: 30mm 60mm 30mm 60mm; row-gap: 1.5mm; margin-top: 4mm; }
      .meta .label { color: #666; }
      .notes { margin-top: 6mm; }
      .notes p { border: 1px solid #ccc; min-height: 20mm; padding: 3mm; }
      .footer { margin-top: 8mm; color: #999; font-size: 8.5pt; border-top: 1px solid #ddd; padding-top: 2mm; }
    </style>
    </head>
    <body>
      <h1>{{JOB_NAME}}</h1>
      <div class="subtitle">Job Sheet — ShopPilot</div>
      <div class="meta">
        <span class="label">Material</span><span>{{MATERIAL}}</span>
        <span class="label">Sheet size</span><span>{{SHEET_WIDTH}} × {{SHEET_HEIGHT}} mm</span>
        <span class="label">Date</span><span>{{DATE}}</span>
        <span class="label">Toolpaths</span><span>{{TOOLPATH_COUNT}}</span>
      </div>
      <table>
        <thead>
          <tr><th>Name</th><th>Type</th><th>Tool</th><th>Feed (mm/min)</th><th>Depth (mm)</th><th>Time (min)</th></tr>
        </thead>
        <tbody>
        {{TOOLPATH_ROWS}}
        </tbody>
      </table>
      <div class="notes">
        <span class="label">Notes</span>
        <p>{{NOTES}}</p>
      </div>
      <div class="footer">{{FOOTER}}</div>
    </body>
    </html>
    """

    /// One table row per toolpath entry.
    public static func toolpathRows(_ toolpaths: [ToolpathInfo]) -> String {
        toolpaths.map { tp in
            "<tr><td>\(escape(tp.name))</td><td>\(escape(tp.type.displayName))</td>"
                + "<td>\(escape(tp.tool))</td><td>\(String(format: "%.0f", tp.feedRate))</td>"
                + "<td>\(String(format: "%.2f", tp.depth))</td>"
                + "<td>\(String(format: "%.1f", tp.estimatedTime / 60.0))</td></tr>"
        }.joined(separator: "\n")
    }

    /// Fill the bundled template from job-sheet data. Returns the complete
    /// HTML document. Values are HTML-escaped before substitution.
    public static func fill(data: JobSheetData) -> String {
        fill(data: data, template: bundledTemplate)
    }

    /// Fill an arbitrary template (used by tests + future user templates).
    public static func fill(data: JobSheetData, template: String) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .medium
        dateFormatter.timeStyle = .short

        var out = template
        let replacements: [String: String] = [
            "{{JOB_NAME}}": escape(data.jobName),
            "{{MATERIAL}}": escape(data.material),
            "{{SHEET_WIDTH}}": String(format: "%.1f", data.sheetWidth),
            "{{SHEET_HEIGHT}}": String(format: "%.1f", data.sheetHeight),
            "{{DATE}}": escape(dateFormatter.string(from: data.createdAt)),
            "{{NOTES}}": escape(data.notes),
            "{{TOOLPATH_COUNT}}": "\(data.toolpaths.count)",
            "{{TOOLPATH_ROWS}}": toolpathRows(data.toolpaths),
            "{{FOOTER}}": escape("Generated by ShopPilot — \(dateFormatter.string(from: .now))"),
        ]
        for (token, value) in replacements {
            out = out.replacingOccurrences(of: token, with: value)
        }
        return out
    }

    /// HTML-escape user content so values cannot inject markup.
    public static func escape(_ s: String) -> String {
        var out = s
        let map: [(String, String)] = [
            ("&", "&amp;"), ("<", "&lt;"), (">", "&gt;"),
            ("\"", "&quot;"), ("'", "&#39;"),
        ]
        for (from, to) in map {
            out = out.replacingOccurrences(of: from, with: to)
        }
        return out
    }
}
