import Foundation
import ShopPilotCore

/// SPK-1102g verify (CLT machines, no XCTest).
/// Proves GRBL post export from the FULL toolpath tree — not the last
/// single-op `gcodeLines` overwrite:
///   1. A two-op tree (Profile + Pocket, real engine G-code) concatenates in
///      tree order; the post-processed output preserves EVERY cut move from
///      BOTH ops (line parity) — a last-op-only export would be shorter.
///   2. GRBL init/cleanup wrapper is correct: header, G21/G90/M8, M9,
///      G0 Z5.0, M2, % framing.
///   3. Golden: a minimal known input post-processes to the exact expected
///      string (normalized).
/// The session save path (allToolpathGCode → CutToMachineBridge) is the app
/// glue covered by the build; this proves the engine chain it relies on.

enum VerifyError: Error { case failed(String) }

func expect(_ cond: Bool, _ msg: String) throws {
    if !cond { throw VerifyError.failed(msg) }
}

func makeClosedRect() -> VectorPath {
    VectorPath(
        points: [
            VectorPoint(x: 0, y: 0), VectorPoint(x: 50, y: 0),
            VectorPoint(x: 50, y: 50), VectorPoint(x: 0, y: 50), VectorPoint(x: 0, y: 0),
        ],
        isClosed: true
    )
}

/// Mirror of AppSession.allToolpathGCode: every computed node's result, in
/// tree order.
func fullTreeGCode(from tree: ToolpathTreeManager) -> [String] {
    tree.allNodes
        .filter { $0.toolpathResult != nil }
        .flatMap { ($0.toolpathResult ?? "").components(separatedBy: .newlines) }
        .filter { !$0.trimmingCharacters(in: .whitespaces).isEmpty }
}

func main() throws {
    // ── 1. Two-op tree, real engines, concatenated buffer. ───────────────────
    let tree = ToolpathTreeManager()
    let vectors = [makeClosedRect()]

    let profile = ProfileToolpathEngine.compute(
        vectors: vectors, params: ProfileToolpathParams(),
        material: nil, stockHeightMm: 6.0
    )
    let pocket = PocketToolpathEngine.compute(
        vectors: vectors, params: PocketToolpathParams(),
        material: nil, stockHeightMm: 25.0
    )

    let profileNode = tree.addOperation("Profile 1")
    profileNode.toolpathResult = profile.gcodeLines.joined(separator: "\n")
    let pocketNode = tree.addOperation("Pocket 1")
    pocketNode.toolpathResult = pocket.gcodeLines.joined(separator: "\n")

    let buffer = fullTreeGCode(from: tree)
    let rawCutMoves = buffer.filter { $0.hasPrefix("G1") }
    try expect(rawCutMoves.count >= 5, "full tree buffer carries real cut moves from both ops")

    // ── 2. Post the FULL tree; every move survives (not last-op only). ───────
    let post = GRBLPostProcessor.grbl().process(gcodeLines: buffer)
    let outputLines = post.gcodeString.components(separatedBy: .newlines)
    let postedCutMoves = outputLines.filter { $0.hasPrefix("G1") || $0.hasPrefix("N10 G1") }
    try expect(
        postedCutMoves.count == rawCutMoves.count,
        "post preserves every cut move from the full tree (\(rawCutMoves.count) raw → \(postedCutMoves.count) posted)"
    )

    // Wrapper: init + cleanup + framing.
    try expect(outputLines.contains("G21 ; Set millimeter units"), "GRBL mm init present")
    try expect(outputLines.contains("G90 ; Absolute positioning"), "GRBL absolute init present")
    try expect(outputLines.contains("M8 ; Flood coolant on"), "coolant on present")
    try expect(outputLines.contains("M9 ; Coolant off"), "coolant off present")
    try expect(outputLines.contains("G0 Z5.0 ; Rapid to safe height"), "safe-height retract present")
    try expect(outputLines.contains("M2 ; Program end"), "program end present")
    try expect(outputLines.first == "%" && outputLines.last == "%", "output framed with %")
    try expect(post.fileName == "toolpath.gcode", "GRBL post labels .gcode")

    // ── 3. Golden: minimal known input → exact expected output. ──────────────
    let goldenPost = GRBLPostProcessor.grbl().process(gcodeLines: ["G0 X0 Y0", "G1 X10 Y0 F300"])
    let golden = """
    %
    (Machine: ShopPilot)
    (Post Processor: GRBL 1.1)
    (Generated by ShopPilot)

    G21 ; Set millimeter units
    G90 ; Absolute positioning
    M8 ; Flood coolant on

    G0 X0 Y0
    G1 X10 Y0 F300

    M9 ; Coolant off
    G0 Z5.0 ; Rapid to safe height
    M2 ; Program end
    %
    """
    if goldenPost.gcodeString != golden {
        print("--- ACTUAL ---")
        print(goldenPost.gcodeString.debugDescription)
        print("--- EXPECTED ---")
        print(golden.debugDescription)
    }
    try expect(goldenPost.gcodeString == golden, "golden post output matches hand-written reference")

    print("ShopPilotVerify1102g: PASS — full-tree export (move parity), GRBL wrapper, golden post")
}

do {
    try main()
} catch {
    print("ShopPilotVerify1102g: FAIL — \(error)")
    exit(1)
}
